name: Build to docs folder for GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-to-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Build site into docs/
        run: bundle exec jekyll build -d docs
        env:
          JEKYLL_ENV: production

      - name: Commit and push docs folder
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs
          git commit -m "Deploy site to docs folder" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.CHIRPY_DEPLOY_TOKEN }}@github.com/sneha-dq/chirpy-blog.git master
